# Generated by Django 3.2.5 on 2021-07-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='debt_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_name', models.CharField(max_length=50)),
                ('debt_balance', models.PositiveSmallIntegerField(default=0)),
                ('debt_rate', models.FloatField(default=0.0)),
                ('debt_im', models.FloatField(default=0)),
            ],
        ),
    ]
