# Generated by Django 3.2.5 on 2021-07-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_app', '0002_remove_debt_item_debt_im'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt_item',
            name='debt_balance',
            field=models.FloatField(default=0),
        ),
    ]
