# Generated by Django 3.2.5 on 2021-07-27 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debt_app', '0003_alter_debt_item_debt_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debt_item',
            old_name='debt_rate',
            new_name='debt_interest_rate',
        ),
    ]
